# Generated by Django 5.0.6 on 2026-10-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gps_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
