# Generated by Django 5.0.6 on 2026-10-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_vehiclelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('service', 'Routine Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('tyres', 'Tyres'), ('oil_change', 'Oil Change'), ('brakes', 'Brakes'), ('electrical', 'Electrical'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='dashboard.vehicle')),
            ],
        ),
    ]
