# Generated by Django 5.0.6 on 2026-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_name', models.CharField(default='My Fleet', max_length=150)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('default_speed_limit', models.DecimalField(decimal_places=2, default=80, max_digits=6)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
